language: python
addons:
  apt:
    sources:
      - deadsnakes
    packages:
      - python3.5
      - python3.6
env:
  - TOXENV=py27-django-111
  - TOXENV=py34-django-111
  - TOXENV=py34-django-20
  - TOXENV=py35-django-111
  - TOXENV=py35-django-20
  - TOXENV=py35-django-master
  - TOXENV=py36-django-111
  - TOXENV=py36-django-20
  - TOXENV=py36-django-master
matrix:
  fast_finish: true
  allow_failures:
    - env: TOXENV=py34-django-master
    - env: TOXENV=py35-django-master
    - env: TOXENV=py36-django-master
install:
    - pip install tox
script:
  - tox