build: false  # Not a C# project, build stuff at the test step instead.
environment:
  global:
    PYTHON: C:/Python27
  matrix:
    - TOXENV=py27-django-18
    - TOXENV=py27-django-111
    - TOXENV=py34-django-111
    - TOXENV=py34-django-20
    - TOXENV=py35-django-111
    - TOXENV=py35-django-20
    - TOXENV=py35-django-master
    - TOXENV=py36-django-111
    - TOXENV=py36-django-20
    - TOXENV=py36-django-master
matrix:
  allow_failures:
    - TOXENV: py34-django-master
    - TOXENV: py35-django-master
    - TOXENV: py36-django-master
install:
  - SET PATH=%PYTHON%;%PYTHON%/Scripts;%PATH%
  - pip install -U tox virtualenv
test_script:
  - tox

