# docs at https://www.appveyor.com/docs/lang/python/
build: off
environment:
  global:
    PYTHON: C:/Python27
  matrix:
    - TOXENV=py27-django-111
    - TOXENV=py34-django-111
    - TOXENV=py34-django-20
    - TOXENV=py35-django-111
    - TOXENV=py35-django-20
    - TOXENV=py35-django-master
    - TOXENV=py36-django-111
    - TOXENV=py36-django-20
    - TOXENV=py36-django-master
  allow_failures:
    - TOXENV: py34-django-master
    - TOXENV: py35-django-master
    - TOXENV: py36-django-master
install:
  - SET PATH=%PYTHON%;%PYTHON%/Scripts;%PATH%
  - pip install -U tox virtualenv
test_script:
  - tox

